apiVersion: v1
kind: Service
metadata:
  name: satisfactory
spec:
  type: LoadBalancer
  ports:
  - port: 7777
    targetPort: 7777
    protocol: TCP
    name: tcp
  - port: 7777
    targetPort: 7777
    protocol: UDP
    name: udp
